import React from 'react';

const TermsAndConditions = () => {


    return (
        <div className="terms">
            <div className="terms-conditions">
                <h1>2TM Limited, trading as Top Gizzit, Terms and Conditions</h1>
                <p>Before progressing with your order, we will need confirmation that you agree to the terms and conditions of sale. It is strongly recommended to read this document in full and to keep a copy for your own records. By entering into a business agreement with 2TM Limited you agree to comply with and be bound by the following terms and conditions of sale. From here on ‘you’ refers to the customer and ‘us’/’we’/’our’ refers to 2TM Limited trading as Top Gizzit.</p>
                <p>By purchasing Goods from us and by entering into this Contract with us, you are warranting that you are acting in the course of your trade or business.</p>
                <p>A reference to a particular law is a reference to it as it is in force for the time being taking account of any amendment, extension, application or re-enactment and includes any subordinate legislation for the time being in force made under it. Any EU law, directive or regulation which currently applies to this contract shall, in the event of the UK’s departure from the EU, have its applicability superseded by any replacing English or Welsh act or statutory instrument.</p>
                <p>Words in the singular include the plural and in the plural include the singular.</p>
                <p>Each of the paragraphs of these Terms & Conditions operates separately. If any court or relevant authority decides that any of them are unlawful, the remaining paragraphs remain in full force and effect. These Terms & Conditions are governed by English law. You and we both agree to submit to the exclusive jurisdiction of the English courts.</p>
                <p>Condition headings do not affect the interpretation of these conditions.</p>
                <h3>1. Pricing and Terms</h3>
                <p>1.1 Quotes are valid for the goods specified in them and for 28 days from date of quote. Please bear in mind that all quotes made are made subject to the terms and conditions of sale. Any order placed is subject to the terms and conditions set out here, as stated on the invoice.</p>
                <p>1.2 The price payable for the goods you order and their delivery is as set out in the placed order invoice. We reserve the right to change the prices shown at any time and we will contact you before the order is confirmed in the event of an alteration being made. An amount equal to the appropriate taxes will be added to the invoice where there is a legal obligation to collect such taxes. Customers will pay this amount in full to us unless they provide us with a valid tax exemption certificate authorised by the appropriate taxing authority e.g. if an EU member state client is VAT registered in their state and therefore is exempt from UK VAT.</p>
                <p>1.3 Misplaced Goods, Misplaced Decimal Places or Otherwise If, by genuine mistake, we have under priced an item, we will not be liable to supply that item to you at the stated price, provided that we notify you before we despatch the item. In those circumstances, we will notify the correct price to you so you can decide whether or not you wish to order the item at that price.</p>
                <p>1.4 Loss of Earnings We cannot, and will not, be held responsible for any loss of earnings, real or projected, as a result of an order being lost, arriving late, or not being as expected.</p>
                <h3>2. Ordering</h3>
                <p>2.1 Terms – We must receive payment IN FULL as specified in your Order confirmation email before the order can be processed. By placing an order, you agree to pay pro-forma for the invoiced goods. Pro-forma payment is not required when a credit agreement is in place, or if stated otherwise on the invoice. Our acceptance of your order brings into existence a legally binding contract between us and you. Customers are reminded that they should satisfy themselves that the products they are ordering are suitable for their requirements before placing an order. No responsibility is placed with 2TM Limited for the decision to order.</p>
                <p>2.2 Orders – All orders will be set out in an order confirmation email and the payment details must to followed for an order to proceed. Responsibility for the accuracy of this order confirmation email lies solely with the customer: mistakes cannot and will not be replaced once your order has entered the production process. By paying the requested payment details means you have agreed to all of our Trading Terms and Conditions. All payments must be in full and in Great British Pounds Sterling (£GBP). Conversion fees from foreign currencies must be borne by the customer and not deducted from the total.</p>
                <p>2.3 Returns – This is a bespoke manufacturing service whereby we manufacture goods to your specifications and therefore refunds and returns of goods are not possible. We will accept no returns of products – blank or customised – for any reason, therefore we encourage customers to take care with the specifications and take care to understand the terms and conditions of their order. By paying for the goods listed you understand that no refund, replacement or compensation (outside of the RSC Manufacturer's warranty) can be claimed for the goods once the order has been placed.</p>
                <p>2.4 Turnaround Time – Our expected order turnaround is 5 months. This can be longer on occasions. You will be given a provisional completion date upon order payment. All turnaround durations are estimates and we cannot guarantee exact delivery dates. We will not be liable for any loss incurred due to production or delivery delays. We are unable to provide prior warning of unforeseen delays.</p>
                <p>2.5 Cancellations and Refunds – Once an order has been placed and the manufacturing stage starts costs are bourne immediately by us. Therefore we stress that once an order has been placed, it cannot be cancelled. Returns and refunds cannot be accepted as stated in 2.3.</p>
                <p>2.6 Repairs - Where there has been genuine manufacturing error you should contact RSC Watches via the warranty card provided with your order.</p>
                <h3>3. Delivery</h3>
                <p>3.1 Shipping – The liability for loss or damage in transit, or thereafter, shall pass to the customer upon the delivery of the order to a common carrier for shipment. Shipping dates are approximate and are based, to a great extent, on prompt receipt by us of all necessary ordering information from you. The customer shall bear all costs of transportation and insurance. We will add transportation costs to your invoice. We shall not be in default by reason of any failure in its performance under this Agreement if such failure results from, whether directly or indirectly, fire, explosion, strike, freight embargo, Act of God or of the public enemy, war, civil disturbance, act of any government, de jure or de facto, or agency or official thereof, material or labour shortage, transportation contingencies, unusually severe weather, default of any other manufacturer or a supplier or subcontractor, quarantine, restriction, epidemic, or catastrophe, lack of timely instructions or essential information from you, or otherwise arisen out of causes beyond our control. Nor shall we at any time be liable for any incidental, special or consequential damages. The customer shall be responsible for all customs clearance and payment of all charges and duties in the territory The risk passes to the buyer upon leaving us and on delivery to a common carrier. We are not liable for any losses in transit.</p>
                <p>3.2 Delays Beyond Our Control – We shall have no liability to you for any failure or delay in the delivery of goods ordered, or for damage or defect to goods caused by events or circumstances beyond our reasonable control (including, without limitation, strikes, lockouts and other industrial disputes).</p>
                <p>3.3 Packaged Deliveries – Orders will arrive boxed in a protective outer box.</p>
                <p>3.4 In the event that you fail to accept any delivery, that delivery shall be deemed to have occurred and any storage or other costs incurred by the Seller as a result of the Buyer’s failure shall be added to the Buyer’s account with interest.</p>
                <p>3.5 Each delivery shall constitute a separate contract, which shall be subject to these terms, and conditions.</p>
                <h3>4. Additional Terms</h3>
                <p>4.1 Exclusion of Liability – We shall not be liable in any way for any loss of revenue, profit, goodwill or any consequential or indirect or special loss or damage arising out of the purchase of any goods by you from us or late or non-delivery of goods. We do not accept liability for any loss from claims of third parties arising out of the use of Goods or Services purchased from us. We shall not be liable for any misrepresentations. We accept zero liability for all losses not specifically mentioned here, as well as any liability for health issues that may occur from the use of products supplied to you by us.</p>
                <p>4.2 Liability – 2TM Limited will not accept any liability for loss or profit or consequential losses suffered as a result of erroneous delivery, production or delivery delay, or otherwise. The risk inherent in all goods passes to the customer as soon as production is complete and the order is dispatched. We are not able to cancel an order where a delay occurs in delivery or production.</p>
                <p>4.3 Governing Law – The contract between you and us shall be governed by and interpreted in accordance with English law, and the English courts shall have exclusive jurisdiction to resolve any arising disputes.</p>
                <p>4.4 Confidentiality – All information supplied by either party to the other and identified as confidential by the recipient shall be kept strictly confidential by the recipient and shall not be disclosed to any third party without the other’s prior written consent. Each party shall take appropriate steps to ensure that its employees, subcontractors and agents are also bound by confidentiality undertakings with respect to products, suppliers, printers, supply chain, supply partners. All confidential information and documents supplied to either party shall be returned to the supplying party on expiry or termination of this Agreement. The obligations of confidentiality in these Terms and Conditions shall remain in force after expiry or termination or any relationship between you and us.</p>
                <p>4.5 Intellectual Property – All intellectual property associated with our brand, supply chain, processes and all other relevant elements of our business will remain ours. Customers have no right to use our IP without written permission. This IP may only be used whilst we are your supplier: the agreement to use our IP expires immediately when you change supplier, or when we inform you – whichever comes sooner.</p>
                <p>4.6 Invalidity – If any part of the Terms of Service is unenforceable (including any provision in which we exclude our liability to you) the enforceability of any other part of the Terms of Service will not be affected all other clauses remaining in full force and effect. So far as possible where any clause/sub-clause or part of a clause/sub-clause can be severed to render the remaining part valid, the clause shall be interpreted accordingly. Alternatively, you agree that the clause shall be rectified and interpreted in such a way that closely resembles the original meaning of the clause /sub-clause as is permitted by law.</p>
                <p>4.7 Waiver – If you breach these conditions and we take no action, we will still be entitled to use our rights and remedies in any other situation where you breach these conditions.</p>
                <p>4.8 Entire Agreement – These terms and conditions, delivery details and contract details, set out the whole of our agreement relating to the supply of the goods to you by us. These terms and conditions cannot be varied except where a “Terms and Conditions Variation Form” that is signed by a director of 2TM Limited and will always supersede the customer’s Terms. In particular nothing verbally agreed by any of our representatives should be understood as a variation of these terms and conditions or as an authorised representation about the nature or quality of any goods offered for sale by us. We shall have no liability for any such representation being untrue or misleading unless it is made fraudulently. No delay or failure on our part to enforce our rights or remedies under these Terms and Conditions shall constitute a waiver on our part or such rights or remedies unless such waiver is confirmed in writing.</p>
                <p>These Terms and conditions are legally binding.</p>
                <br/>
                <p>2TM Limited T.A. Top Gizzit</p>
                <p>Registered in England & Wales</p>
                <p>Company Number – 12532310</p>
                <p>11 Tresooth Court Anchor Quay</p>
                <p>PENRYN</p>
                <p>TR10 8GY</p>
            </div>
        </div>

    );
};


export default TermsAndConditions;
